[package]
name = "kaniko-login"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
serde = { version = "1.0.209", features = ["std", "derive"] }
serde_json = "1.0.127"
base64 = "0.22.1"
